services:
  manyai_bot:
    working_dir: /app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    command: sh -c "uvicorn main:create_webhook --host 0.0.0.0 --port ${APP_PORT}"
    expose:
      - ${APP_PORT}
    env_file:
      - .env